version: 2.1
jobs:
  lint-dockerfile:
    docker:
      - image: circleci/python:3.8

    steps:
      - checkout

      # Install Hadolint
      - run:
          name: Install Hadolint
          command : |
            sudo wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v2.9.0/hadolint-Linux-x86_64
            sudo chmod +x /bin/hadolint

      # Lint Dockerfile
      - run:
          name: Lint Dockerfile
          command: |
            hadolint Dockerfile
            
  test-golang-app:
    docker:
      - image: golang:1.15

    steps:
      - checkout

      # Install dependencies
      - run:
          name: Install dependencies
          command: go mod download

      # Run tests
      - run:
          name: Run tests
          command: go test -v -short --count=1 $(go list ./...)

  build-and-push:
    docker:
      - image: docker:20.10.9
    working_directory: ~/karsajobs

    steps:
      - checkout

      - setup_remote_docker

      - run:
          name: Run Bash Script
          command: |
            set -e
            sh ./build_push_image_karsajobs.sh

workflows:
  version: 2
  lint-and-test:
    jobs:
      - lint-dockerfile
      - test-golang-app
      - build-and-push